const Discord = require("discord.js");

module.exports.run = async (bot, message, args) => {

        //kod başlangıç
        let yazan = message.author.username
        
            message.channel.send(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **120**`)
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **119**`))
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **118**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **117**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **116**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **115**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **114**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **113**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **112**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **111**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **110**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **109**`))
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **108**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **107**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **106**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **105**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **104**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **103**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **102**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **101**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **100**`))
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **99**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **98**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **97**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **96**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **95**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **94**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **93**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **92**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **91**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **90**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **89**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **88**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **87**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **86**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **85**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **84**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **83**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **82**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **81**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **80**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **79**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **78**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **77**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **76**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **75**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **74**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **73**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **72**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **71**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **70**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **69**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **68**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **67**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **66**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **65**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **64**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **63**`))
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **62**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **61**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **60**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **59**`))
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **58**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **57**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **56**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **55**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **54**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **53**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **52**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **51**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **50**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **49**`))
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **48**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **47**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **46**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **45**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **44**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **43**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **42**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **41**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **40**`))
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **39**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **38**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **37**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **36**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **35**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **34**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **33**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **32**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **31**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **30**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **29**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **28**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **27**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **26**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **25**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **24**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **23**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **22**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **21**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **20**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **19**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **18**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **17**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **16**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **15**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **14**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **13**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **12**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **11**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **10**`)) 
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **9**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **8**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **7**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **6**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **5**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **4**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **3**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **2**`))     
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımının Bitmesine = **1**`))    
            .then((message)=>  message.edit(`${yazan} Adlı Kişinin Gerisayımı **BİTTİ!**`)) 

            

              


        //kod bitiş
}

module.exports.help = {
    name: "gerisayım2dk"
}